CUDNN:
  BENCHMARK: true
  DETERMINISTIC: false
  ENABLED: true

DATASET:
  NUM_CLASSES: 6

MODEL:
  NAME: pidnet_small
  NUM_OUTPUTS: 2
  PRETRAINED: 'checkpoints/segmentation/pidNet_wieghts.pt'

TEST:
  IMAGE_SIZE: [1280, 720]
  OUTPUT_INDEX: -1